import type { Config } from "@shared/schema";

export const DEFAULT_CONFIG: Config = {
  githubTokens: [],
  webUsername: "",
  webPassword: "",
  codingAgent: "claude",
  fallbackToNextCodingAgent: false,
  codexModel: "",
  codexReasoningEffort: "default",
  claudeModel: "opus",
  claudeEffort: "default",
  maxTurns: 15,
  batchWindowMs: 600000,
  pollIntervalMs: 600000,
  maxChangesPerRun: 20,
  autoResolveMergeConflicts: true,
  autoCreateReleases: false,
  autoUpdateDocs: true,
  autoPrs: true,
  autoIssues: true,
  includeRepositoryLinksInGitHubComments: true,
  githubCommentAppName: "patchdeck",
  postGitHubProgressReplies: false,
  autoHealCI: false,
  maxHealingAttemptsPerSession: 3,
  maxHealingAttemptsPerFingerprint: 2,
  maxConcurrentHealingRuns: 1,
  healingCooldownMs: 900000,
  autoHealDeployments: false,
  deploymentCheckDelayMs: 120000,
  deploymentCheckTimeoutMs: 900000,
  deploymentCheckPollIntervalMs: 60000,
  maxConcurrentIssueEvaluations: 2,
  maxConcurrentIssueWork: 1,
  maxConcurrentBabysitRuns: 3,
  watchedRepos: [],
  trustedReviewers: [],
  priorityIssueAuthors: [],
  ignoredBots: ["dependabot[bot]", "codecov[bot]", "github-actions[bot]"],
};
